### ISSUE TITLE
VERBOSE does not change anything

### ISSUE THREAD

**Issue by DanielVandH** [SciML/TruncatedStacktraces.jl#2]
```julia
julia> using TruncatedStacktraces;

julia> TruncatedStacktraces.VERBOSE[] = false;

julia> v
ERROR: UndefVarError: v not defined

Some of the types have been truncated in the stacktrace for improved reading. To emit complete information
in the stack trace, evaluate `TruncatedStacktraces.VERBOSE[] = true` and re-run the code.


julia> TruncatedStacktraces.VERBOSE[] = true;

julia> v
ERROR: UndefVarError: v not defined

Some of the types have been truncated in the stacktrace for improved reading. To emit complete information
in the stack trace, evaluate `TruncatedStacktraces.VERBOSE[] = true` and re-run the code.
```

Doesn't look like VERBOSE does anything here - I also question whether this error message should be printed when no types are even present in the error message. Perhaps the `init` function in the src file needs to be something like

```julia
function __init__()
    for type in InteractiveUtils.subtypes(Exception)
        if type == MethodError
            Base.Experimental.register_error_hint(type) do io, e, args, kwargs
                VERBOSE[] && println(io, VERBOSE_MSG)
            end
        else
            Base.Experimental.register_error_hint(type) do io, e
                VERBOSE[] && println(io, VERBOSE_MSG)
            end
        end
    end
end
```

or maybe `VERBOSE[]` goes before `Base.Experimental.register_error_hint(type)` - I'm not really sure what `register_error_hint` does.

**Comment by ChrisRackauckas** [comment]
It changes whether the stacktraces are truncated or not, for type printing which has opted in. But it does not change whether the message is printed or not.

> Doesn't look like VERBOSE does anything here - I also question whether this error message should be printed when no types are even present in the error message. Perhaps the init function in the src file needs to be something like

I think your modification is fine, except it should be `!VERBOSE[]`. I'd accept a PR for that. But indeed with the implementation of error hints we do not have enough information to check the whole stack trace and look for types which have opted in. A check for the unicode `...` would actually be a good enough heuristic, where print if that's in there otherwise not. But sadly we do not have enough tools in Base to make that kind of decision, so I would prefer to print more often than not. But indeed if someone has already set VERBOSE[]=true then there's no reason to keep printing it, so this change looks reasonable.

**Comment by DanielVandH** [comment]
Interesting - didn't realise there would be some limitations with what's in base. I put in a PR for the change I made. This could probably be closed after that's in.

**Comment by ChrisRackauckas** [comment]
I wonder if we should add a Preferences.jl preference to allow turning it on and off statically.

**Comment by ChrisRackauckas** [comment]
Preferences have been added.
